title: Regularízate Digital
email: hola@regularizate.digital
description: >-
  La plataforma líder para la regularización de extranjeros en España. 
  Trámites digitales, rápidos y sin cita previa.
baseurl: ""
url: "https://www.regularizate.digital" 
permalink: /:title/
